general:
    debug: false
    debug-level: low
    check-for-updates: true
    simplify-time: false
mysql:
    hawkeye-table: hawkeye
    port: 3306
    player-table: hawk_players
    username: root
    world-table: hawk_worlds
    hostname: localhost
    max-connections: 10
    password: ''
    database: minecraft