author: iTidez
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.itidez.plugins.icart.Icart
name: iCart
startup: postworld
url: http://derpcraft.co/
version: '1.01B'
